### ISSUE TITLE
Incomplete transfer of DAM without error

### ISSUE THREAD

**Issue by soujiro32167** [TWCable/grabbit#170]
Hi

I am trying to transfer a DAM path with 4737 assets. However, this is the result I get from Grabbit every time: 

```json
{
        "endTime": "2017-01-16T22:48:46+0000",
        "exitStatus": {
            "exitCode": "COMPLETED",
            "exitDescription": "",
            "running": false
        },
        "jcrNodesWritten": 398,
        "jobExecutionId": 4067630146893983297,
        "path": "/content/dam/estore",
        "startTime": "2017-01-16T22:47:11+0000",
        "timeTaken": 95151,
        "transactionID": 3971212595291231010
    }
```

Looking at the logs, there are no errors. Running in DEBUG mode reveals that the process always (5 tries) ends just before the original rendition of a ~400MB .zip file: 

```
/content/dam/estore/popup/Autodesk_Realtime_Renderer_Tutorial_en.zip/jcr:content/renditions/cq5dam.web.1280.1280.jpeg, /jcr:content]
17.01.2017 19:19:57.002 *INFO* [clientJobLauncherTaskExecutor-7] com.twcable.grabbit.client.batch.steps.jcrnodes.JcrNodesWriter StopWatch 'Refreshing session: session-6804754': running time (millis) = 0
17.01.2017 19:19:57.009 *INFO* [clientJobLauncherTaskExecutor-7] com.twcable.grabbit.client.batch.steps.jcrnodes.LoggingStepExecutionListener JcrNodes Step Complete. Current Path : /content/dam/estore . Total nodes written : 398
```

Is there a size limit to transferred nodes? Or perhaps some sort of connection timeout that would cause the transfer to stop without error?

**Comment by jbornemann** [comment]
Hey @soujiro32167,

Could you provide an example configuration based off the configuration you used to produce this? What AEM version are you running?

Are you running a delta sync? If so - if the asset was successfully synched previously, and not updated on the sending server - it would not be sent across, regardless of it's state on the receiving server - for e.g, if it was since deleted.

Can you try to sync just the 400MB asset, ensuring delta sync is off?

Either a connection timeout, or hitting technical size limitations I would expect to result in a job failure.

**Comment by soujiro32167** [comment]
Thanks for the quick response! I'll try to migrate the file alone and send over the config

**Comment by soujiro32167** [comment]
```yaml
# Client Type: author

   # Information for connecting to the source content
   serverUsername : ''
   serverPassword : ''
   serverScheme : http
   serverHost : ''
   serverPort : 4502

   deltaContent : true # default for all the paths

   # A reference to the standard set of workflow configuration ids that
   # we want to turn off when working with DAM assets.
   damWorkflows: &ourDamWorkflows
     - /etc/workflow/launcher/config/update_asset_mod
     - /etc/workflow/launcher/config/update_asset_create
     - /etc/workflow/launcher/config/dam_xmp_nested_writeback
     - /etc/workflow/launcher/config/dam_xmp_writeback


   # Each of the paths to include in the copy
   pathConfigurations :
    -
      path : /content/dam/estore
      workflowConfigIds : *ourDamWorkflows
      deltaContent : false
      deleteBeforeWrite : true
```
